// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
import { Room } from "../../types/Room";

type Response = {
  rooms: Room[];
};

const response: Response = {
  rooms: [
    {
      __typename: "Room",
      id: "",
      name: "Tabletop Gaming Tycoon",
      description:
        'As your team sifts through your board game collection, you find yourself tired of all the usual options. To spice things up, you all decide to make your own! In this business simulation, you\'ll make both creative and financial decisions in an attempt to make the most interesting tabletop game of all time! ("This business simulation is great for anyone who liked Video Game Empire or Ice Cream Royalty.")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-08T21:00:00.000Z",
      endsAt: "2021-07-08T21:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1620423433/enhzy1bmptknihmtacqb.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Welcome to Rooms",
      description:
        "This is a great place for anyone new to Primer Rooms to get to know each other as well as a few members of the Primer team! We'll talk about how Rooms work, what to expect, and how to best get set up at home. Just visit this page when it's time for the room to start and click the join button!",
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-12T18:00:00.000Z",
      endsAt: "2021-07-12T18:30:00.000Z",
      durationInMinutes: 30,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1616182993/i4njlqn0eq0dgw24xwi9.png",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-07-06T16:06:01.470Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "When in the World",
      description:
        'In this episode of Where in the World, your team is taking a break from traveling across the globe — instead, you\'ll be traveling across time! Use online research and tricky clues to go on an adventure through history. (This activity is great for anyone who liked previous episodes of "Where in the World?")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-09T17:00:00.000Z",
      endsAt: "2021-07-09T17:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1620258746/bqszzep19fxzzyuqti9d.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Mystery of the Abandoned Amusement Park",
      description:
        'No one has visited the Old Town\'s amusement park in years, but recently there have been reports of rides suddenly turning on and running completely empty. The city wants the investigation kept under wraps so that residents aren\'t spooked — can you get to the bottom of it? (This mystery is great for anyone who liked "The Missing Portrait" or "Mystery Aboard the ISS.")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-09T21:00:00.000Z",
      endsAt: "2021-07-09T21:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1624051147/vuzzfdd3jbw0hnndrae0.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Soundtrap Studio",
      description:
        'Jam on some new beats with your fellow musicians and Music club expert T.J. in another Soundtrap Studio! If you\'re new to Soundtrap, check out the "Get Started with Soundtrap" project guide for tips on getting started. Note: this activity will meet on Zoom, and you can join using the same Join button here!',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-12T18:00:00.000Z",
      endsAt: "2021-07-12T18:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1616182994/shenpjxkfbf878g4bhmo.png",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-07-06T16:06:01.470Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Cooking Club Meetup",
      description:
        "Come meet other members of the Cooking Club! We'll decide as a group what kinds of activities, discussion topics, and more we want to do together.",
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-12T22:00:00.000Z",
      endsAt: "2021-07-12T22:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1616183049/yisxddalljzgqzutk0ah.png",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-07-06T16:06:01.470Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Mystery of the Abandoned Amusement Park",
      description:
        'No one has visited the Old Town\'s amusement park in years, but recently there have been reports of rides suddenly turning on and running completely empty. The city wants the investigation kept under wraps so that residents aren\'t spooked — can you get to the bottom of it? (This mystery is great for anyone who liked "The Missing Portrait" or "Mystery Aboard the ISS.")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-09T18:00:00.000Z",
      endsAt: "2021-07-09T18:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1624051147/vuzzfdd3jbw0hnndrae0.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Airline Antics",
      description:
        "Your team is taking a tour around Primair Airlines' home airport: San Francisco International Airport. While you're there, you'll get to check out the various departments and see what it's like to run one of the most hectic businesses in the world!",
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-12T21:00:00.000Z",
      endsAt: "2021-07-12T21:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1621044181/un4ngomo0niihuuuv5j0.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-07-06T16:06:01.470Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Mystery of the Abandoned Amusement Park",
      description:
        'No one has visited the Old Town\'s amusement park in years, but recently there have been reports of rides suddenly turning on and running completely empty. The city wants the investigation kept under wraps so that residents aren\'t spooked — can you get to the bottom of it? (This mystery is great for anyone who liked "The Missing Portrait" or "Mystery Aboard the ISS.")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-08T17:00:00.000Z",
      endsAt: "2021-07-08T17:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1624051147/vuzzfdd3jbw0hnndrae0.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Mystery of the Abandoned Amusement Park",
      description:
        'No one has visited the Old Town\'s amusement park in years, but recently there have been reports of rides suddenly turning on and running completely empty. The city wants the investigation kept under wraps so that residents aren\'t spooked — can you get to the bottom of it? (This mystery is great for anyone who liked "The Missing Portrait" or "Mystery Aboard the ISS.")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-09T19:00:00.000Z",
      endsAt: "2021-07-09T19:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1624051147/vuzzfdd3jbw0hnndrae0.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "When in the World",
      description:
        'In this episode of Where in the World, your team is taking a break from traveling across the globe — instead, you\'ll be traveling across time! Use online research and tricky clues to go on an adventure through history. (This activity is great for anyone who liked previous episodes of "Where in the World?")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-09T20:00:00.000Z",
      endsAt: "2021-07-09T20:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1620258746/bqszzep19fxzzyuqti9d.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Naturalists Club Meetup",
      description:
        "Come meet other members of the Naturalists Club! We'll decide as a group what kinds of activities, discussion topics, and more we want to do together.",
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-08T20:00:00.000Z",
      endsAt: "2021-07-08T20:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1616182995/gtubbfdf5rq4fajkf0da.png",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Airline Antics",
      description:
        "Your team is taking a tour around Primair Airlines' home airport: San Francisco International Airport. While you're there, you'll get to check out the various departments and see what it's like to run one of the most hectic businesses in the world!",
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-12T20:00:00.000Z",
      endsAt: "2021-07-12T20:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1621044181/un4ngomo0niihuuuv5j0.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-07-06T16:06:01.470Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Pet Adoption Club",
      description:
        'Your team is taking on the job of running a pet adoption center. Between taking care of the animals and talking with potential pet parents, you\'ll need to come up with innovative ways to get as many lovely animals adopted as possible! ("This business simulation is great for anyone who liked Flea Market Royalty or Amusement Park Tycoon.")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-08T19:00:00.000Z",
      endsAt: "2021-07-08T19:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1616183050/hff4lc8sz8mczxz60ofw.png",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Scratch Arcade",
      description:
        "Calling all Game-Makers: join other Scratch fans to come play some games and talk about game design! We'll play a few games together while chatting about what we like and don't like. ",
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-12T19:00:00.000Z",
      endsAt: "2021-07-12T19:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1620423433/enhzy1bmptknihmtacqb.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-07-06T16:06:01.470Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Pet Adoption Club",
      description:
        'Your team is taking on the job of running a pet adoption center. Between taking care of the animals and talking with potential pet parents, you\'ll need to come up with innovative ways to get as many lovely animals adopted as possible! ("This business simulation is great for anyone who liked Flea Market Royalty or Amusement Park Tycoon.")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-09T22:00:00.000Z",
      endsAt: "2021-07-09T22:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1620423433/enhzy1bmptknihmtacqb.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Airline Antics",
      description:
        "Your team is taking a tour around Primair Airlines' home airport: San Francisco International Airport. While you're there, you'll get to check out the various departments and see what it's like to run one of the most hectic businesses in the world!",
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-12T17:00:00.000Z",
      endsAt: "2021-07-12T17:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1621044181/un4ngomo0niihuuuv5j0.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-07-06T16:06:01.470Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
    {
      __typename: "Room",
      id: "",
      name: "Tabletop Gaming Tycoon",
      description:
        'As your team sifts through your board game collection, you find yourself tired of all the usual options. To spice things up, you all decide to make your own! In this business simulation, you\'ll make both creative and financial decisions in an attempt to make the most interesting tabletop game of all time! ("This business simulation is great for anyone who liked Video Game Empire or Ice Cream Royalty.")',
      hostType: "PRIMER_HOSTED",
      publicId: "FAKE_PUBLIC_ID",
      url: "https://withprimer.com/rooms/FAKE_URL",
      subtitle: "Open to ages 9+",
      startsAt: "2021-07-08T22:00:00.000Z",
      endsAt: "2021-07-08T22:45:00.000Z",
      durationInMinutes: 45,
      coverImageUrl:
        "https://res.cloudinary.com/primer-cloudinary/image/upload/v1620423433/enhzy1bmptknihmtacqb.jpg",
      hasDefaultUrl: true,
      maxParticipants: 6,
      minAge: 9,
      maxAge: 14,
      createdAt: "2021-06-28T06:32:14.457Z",
      updatedAt: "2021-07-07T16:59:08.385Z",
      isMyAgeAllowed: true,
      hosts: [],
    },
  ],
};

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Response>
) {
  // Adjust dates so that they appear to start today.
  const baseDay = new Date(
    new Date(Date.parse("2021-07-08T12:00:00")).setHours(0, 0, 0, 0)
  );
  const today = new Date(new Date().setHours(0, 0, 0, 0));
  const adjResponse = {
    ...response,
    rooms: response.rooms.map((r, ind) => ({
      ...r,
      id: `${ind}`,
      startsAt: new Date(
        Date.parse(r.startsAt) + today.getTime() - baseDay.getTime()
      ).toISOString(),
      endsAt: new Date(
        Date.parse(r.endsAt) + today.getTime() - baseDay.getTime()
      ).toISOString(),
    })),
  };
  res.status(200).json(adjResponse);
}
